Za pregledanje
nemanjazecevic/Pod-Request pull request #1
Opened 2021-09-28 08:13 UTC by nemanjazecevic

2021-09-28 13:20 UTC, sbozic85 requested changes
Nemanja, mogao bi da ispravis par stvari:
- kada unesem nesto u input polje, bilo ispravnu bilo neispravnu vrednost, i pritisnem Enter, stranica se refreshuje
- stranica ne izgleda dobro na velikim ekranima (pogledaj screenshot)
-  input polje nema dobar font
- na tabletu nije ok sirina input polja i logoa ispod
- na manjim telefonima se poremeti visina stranice

![Screenshot_3](https://user-images.githubusercontent.com/90195863/135094726-da0b1989-481e-4cd0-9173-1454f9a834ee.jpg)

![Screenshot_4](https://user-images.githubusercontent.com/90195863/135094744-3cb96f31-9798-49a7-8910-110651a0b450.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/90195863/135094763-bc54b746-ac00-4962-bc9e-55b56d56690f.jpg)

2021-09-29 14:02 UTC, sbozic85 approved these changes
Dosta bolje izgleda, imas i dalje bug kada se pritisne Enter u input polju, nesto se poremete background image i neka visina

2021-09-29 14:02 UTC, merged

2021-09-29 14:11 UTC, nemanjazecevic commented
Promeni se visina kada se doda label za upozorenje... a mislim da
background image ne isprati to zato sto je to vec maksimalna dimezija
slike/ Nisam siguran da li si na to mislio

On Wed, Sep 29, 2021 at 4:03 PM sbozic85 ***@***.***> wrote:

> Merged #1 <https://github.com/nemanjazecevic/Pod-Request/pull/1> into
> master.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nemanjazecevic/Pod-Request/pull/1#event-5381036502>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOCHOAHOG7P33EJKSZXZQZTUEMMBPANCNFSM5E4ZK2GQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-30 06:12 UTC, sbozic85 commented
Ovaj bug se desava:

https://user-images.githubusercontent.com/90195863/135397101-91140f0f-6d1d-4892-a128-9c54fc10126a.mp4